// 24 Tirthankaras of the present avasarpini time-cycle, in canonical order.
// Lanchhana, complexion, and parentage follow the Digambara tradition.

export type Tirthankara = {
  num: number;
  name: string;
  nameSk: string;
  lanchhana: string;          // Identifying symbol
  lanchhanaSk?: string;
  complexion: string;          // Traditional complexion
  fatherSk: string;
  motherSk: string;
  birthplace?: string;
  mokshaPlace?: string;
  note?: string;
};

export const TIRTHANKARAS: Tirthankara[] = [
  { num: 1, name: 'Rishabhanatha (Adinatha)', nameSk: 'ऋषभनाथ (आदिनाथ)',
    lanchhana: 'Bull', lanchhanaSk: 'वृषभ', complexion: 'Golden',
    fatherSk: 'राजा नाभिराय', motherSk: 'महारानी मरुदेवी',
    birthplace: 'Ayodhya', mokshaPlace: 'Mt. Kailasha (Ashtapada)',
    note: 'The first Tirthankara of this time-cycle. Founded the spiritual order. The Bhaktamara Stotra is composed in his praise.' },
  { num: 2, name: 'Ajitanatha', nameSk: 'अजितनाथ',
    lanchhana: 'Elephant', lanchhanaSk: 'गज', complexion: 'Golden',
    fatherSk: 'राजा जितशत्रु', motherSk: 'महारानी विजया',
    birthplace: 'Ayodhya', mokshaPlace: 'Mt. Sammed Shikhar' },
  { num: 3, name: 'Sambhavanatha', nameSk: 'सम्भवनाथ',
    lanchhana: 'Horse', lanchhanaSk: 'अश्व', complexion: 'Golden',
    fatherSk: 'राजा जितारि', motherSk: 'महारानी सेना',
    birthplace: 'Sravasti', mokshaPlace: 'Mt. Sammed Shikhar' },
  { num: 4, name: 'Abhinandananatha', nameSk: 'अभिनन्दननाथ',
    lanchhana: 'Monkey', lanchhanaSk: 'कपि', complexion: 'Golden',
    fatherSk: 'राजा संवर', motherSk: 'महारानी सिद्धार्था',
    birthplace: 'Ayodhya', mokshaPlace: 'Mt. Sammed Shikhar' },
  { num: 5, name: 'Sumatinatha', nameSk: 'सुमतिनाथ',
    lanchhana: 'Curlew (krauñca)', lanchhanaSk: 'क्रौञ्च', complexion: 'Golden',
    fatherSk: 'राजा मेघप्रभ', motherSk: 'महारानी मङ्गला',
    birthplace: 'Ayodhya', mokshaPlace: 'Mt. Sammed Shikhar' },
  { num: 6, name: 'Padmaprabha', nameSk: 'पद्मप्रभ',
    lanchhana: 'Red lotus', lanchhanaSk: 'रक्त-कमल', complexion: 'Red',
    fatherSk: 'राजा धरण', motherSk: 'महारानी सुसीमा',
    birthplace: 'Kausambi', mokshaPlace: 'Mt. Sammed Shikhar' },
  { num: 7, name: 'Suparshvanatha', nameSk: 'सुपार्श्वनाथ',
    lanchhana: 'Swastika', lanchhanaSk: 'स्वस्तिक', complexion: 'Golden',
    fatherSk: 'राजा सुप्रतिष्ठ', motherSk: 'महारानी पृथ्वी',
    birthplace: 'Varanasi', mokshaPlace: 'Mt. Sammed Shikhar' },
  { num: 8, name: 'Chandraprabha', nameSk: 'चन्द्रप्रभ',
    lanchhana: 'Crescent moon', lanchhanaSk: 'चन्द्र', complexion: 'White',
    fatherSk: 'राजा महासेन', motherSk: 'महारानी लक्ष्मणा',
    birthplace: 'Chandrapuri', mokshaPlace: 'Mt. Sammed Shikhar' },
  { num: 9, name: 'Pushpadanta (Suvidhinatha)', nameSk: 'पुष्पदन्त (सुविधिनाथ)',
    lanchhana: 'Crocodile (makara)', lanchhanaSk: 'मकर', complexion: 'White',
    fatherSk: 'राजा सुग्रीव', motherSk: 'महारानी रामा',
    birthplace: 'Kakandi', mokshaPlace: 'Mt. Sammed Shikhar' },
  { num: 10, name: 'Shitalanatha', nameSk: 'शीतलनाथ',
    lanchhana: 'Śrīvatsa', lanchhanaSk: 'श्रीवत्स', complexion: 'Golden',
    fatherSk: 'राजा दृढरथ', motherSk: 'महारानी सुनन्दा',
    birthplace: 'Bhaddilapura', mokshaPlace: 'Mt. Sammed Shikhar' },
  { num: 11, name: 'Shreyamsanatha', nameSk: 'श्रेयांसनाथ',
    lanchhana: 'Rhinoceros (gaṇḍa)', lanchhanaSk: 'गण्डक', complexion: 'Golden',
    fatherSk: 'राजा विष्णु', motherSk: 'महारानी विष्णुश्री',
    birthplace: 'Simhapuri', mokshaPlace: 'Mt. Sammed Shikhar' },
  { num: 12, name: 'Vasupujya', nameSk: 'वासुपूज्य',
    lanchhana: 'Buffalo (mahiṣa)', lanchhanaSk: 'महिष', complexion: 'Red',
    fatherSk: 'राजा वसुपूज्य', motherSk: 'महारानी जयावती',
    birthplace: 'Champapuri', mokshaPlace: 'Champapuri' },
  { num: 13, name: 'Vimalanatha', nameSk: 'विमलनाथ',
    lanchhana: 'Boar (varāha)', lanchhanaSk: 'वराह', complexion: 'Golden',
    fatherSk: 'राजा कृतवर्मा', motherSk: 'महारानी सुरमा / श्यामा',
    birthplace: 'Kampilya', mokshaPlace: 'Mt. Sammed Shikhar' },
  { num: 14, name: 'Anantanatha', nameSk: 'अनन्तनाथ',
    lanchhana: 'Falcon (śyena)', lanchhanaSk: 'श्येन', complexion: 'Golden',
    fatherSk: 'राजा सिंहसेन', motherSk: 'महारानी सर्वयशा',
    birthplace: 'Ayodhya', mokshaPlace: 'Mt. Sammed Shikhar' },
  { num: 15, name: 'Dharmanatha', nameSk: 'धर्मनाथ',
    lanchhana: 'Vajra', lanchhanaSk: 'वज्र', complexion: 'Golden',
    fatherSk: 'राजा भानु', motherSk: 'महारानी सुव्रता',
    birthplace: 'Ratnapuri', mokshaPlace: 'Mt. Sammed Shikhar' },
  { num: 16, name: 'Shantinatha', nameSk: 'शान्तिनाथ',
    lanchhana: 'Deer (mṛga)', lanchhanaSk: 'मृग', complexion: 'Golden',
    fatherSk: 'राजा विश्वसेन', motherSk: 'महारानी अचिरा',
    birthplace: 'Hastinapur', mokshaPlace: 'Mt. Sammed Shikhar',
    note: 'Also a Chakravartin emperor before renunciation.' },
  { num: 17, name: 'Kunthunatha', nameSk: 'कुन्थुनाथ',
    lanchhana: 'Goat (chāgala)', lanchhanaSk: 'छागल', complexion: 'Golden',
    fatherSk: 'राजा सूर्य', motherSk: 'महारानी श्री',
    birthplace: 'Hastinapur', mokshaPlace: 'Mt. Sammed Shikhar',
    note: 'Also a Chakravartin emperor.' },
  { num: 18, name: 'Aranatha', nameSk: 'अरनाथ',
    lanchhana: 'Nandyāvarta (a śrīvatsa-like figure)', lanchhanaSk: 'नन्द्यावर्त', complexion: 'Golden',
    fatherSk: 'राजा सुदर्शन', motherSk: 'महारानी मित्रसेना',
    birthplace: 'Hastinapur', mokshaPlace: 'Mt. Sammed Shikhar',
    note: 'Also a Chakravartin emperor.' },
  { num: 19, name: 'Mallinatha', nameSk: 'मल्लिनाथ',
    lanchhana: 'Pitcher (kalaśa)', lanchhanaSk: 'कलश', complexion: 'Blue (in Digambara) / Variable',
    fatherSk: 'राजा कुम्भ', motherSk: 'महारानी प्रभावती',
    birthplace: 'Mithila', mokshaPlace: 'Mt. Sammed Shikhar',
    note: 'In Digambara tradition: a male Tirthankara. In Shvetambara tradition: female. This is the most-cited example of doctrinal difference between the traditions.' },
  { num: 20, name: 'Munisuvrata', nameSk: 'मुनिसुव्रत',
    lanchhana: 'Tortoise (kūrma)', lanchhanaSk: 'कूर्म', complexion: 'Black / Dark',
    fatherSk: 'राजा सुमित्र', motherSk: 'महारानी पद्मावती',
    birthplace: 'Rajagriha', mokshaPlace: 'Mt. Sammed Shikhar' },
  { num: 21, name: 'Naminatha', nameSk: 'नमिनाथ',
    lanchhana: 'Blue lotus (nīlotpala)', lanchhanaSk: 'नीलोत्पल', complexion: 'Golden',
    fatherSk: 'राजा विजय', motherSk: 'महारानी वप्रा',
    birthplace: 'Mithila', mokshaPlace: 'Mt. Sammed Shikhar' },
  { num: 22, name: 'Neminatha (Aristanemi)', nameSk: 'नेमिनाथ (अरिष्टनेमि)',
    lanchhana: 'Conch (śaṅkha)', lanchhanaSk: 'शङ्ख', complexion: 'Black / Dark',
    fatherSk: 'राजा समुद्रविजय', motherSk: 'महारानी शिवादेवी',
    birthplace: 'Sauripura (Mathura region)', mokshaPlace: 'Mt. Girnar',
    note: 'Cousin of Krishna in Jain tradition. Renounced the world on his wedding day after seeing animals being slaughtered for the wedding feast.' },
  { num: 23, name: 'Parshvanatha', nameSk: 'पार्श्वनाथ',
    lanchhana: 'Snake (sarpa, with hood)', lanchhanaSk: 'सर्प', complexion: 'Blue / Dark',
    fatherSk: 'राजा अश्वसेन', motherSk: 'महारानी वामा',
    birthplace: 'Varanasi', mokshaPlace: 'Mt. Sammed Shikhar',
    note: 'Historical Tirthankara (~9th–8th century BCE). His teaching of four vows preceded Mahavir, who added the fifth (brahmacarya). Especially venerated; the snake-hood symbol is the most recognizable in Jain iconography.' },
  { num: 24, name: 'Mahavira (Vardhamana)', nameSk: 'महावीर (वर्धमान)',
    lanchhana: 'Lion (siṁha)', lanchhanaSk: 'सिंह', complexion: 'Golden',
    fatherSk: 'राजा सिद्धार्थ', motherSk: 'महारानी त्रिशला (in Shvetambara: also called Priyakarini)',
    birthplace: 'Kundalapura (Vaishali region)', mokshaPlace: 'Pavapuri',
    note: 'The 24th and last Tirthankara of this time-cycle (599–527 BCE in traditional dating). NOT the founder of Jainism — the last in a long line. His teaching emphasized the five great vows and forms the basis of post-canonical Jain practice.' },
];
